// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.4
// source: Extension.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CarthooksExtensionClient is the client API for CarthooksExtension service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CarthooksExtensionClient interface {
	GetCustomFieldTypes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetFieldsResponse, error)
	GetModels(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetModelsResponse, error)
	GetI18NPack(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetI18NPackResponse, error)
	GetServices(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetServicesResponse, error)
	GetConnecotrs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetConnectorsResponse, error)
	GetResource(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetResourcesResponse, error)
}

type carthooksExtensionClient struct {
	cc grpc.ClientConnInterface
}

func NewCarthooksExtensionClient(cc grpc.ClientConnInterface) CarthooksExtensionClient {
	return &carthooksExtensionClient{cc}
}

func (c *carthooksExtensionClient) GetCustomFieldTypes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetFieldsResponse, error) {
	out := new(GetFieldsResponse)
	err := c.cc.Invoke(ctx, "/service.CarthooksExtension/GetCustomFieldTypes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carthooksExtensionClient) GetModels(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetModelsResponse, error) {
	out := new(GetModelsResponse)
	err := c.cc.Invoke(ctx, "/service.CarthooksExtension/GetModels", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carthooksExtensionClient) GetI18NPack(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetI18NPackResponse, error) {
	out := new(GetI18NPackResponse)
	err := c.cc.Invoke(ctx, "/service.CarthooksExtension/GetI18nPack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carthooksExtensionClient) GetServices(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetServicesResponse, error) {
	out := new(GetServicesResponse)
	err := c.cc.Invoke(ctx, "/service.CarthooksExtension/GetServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carthooksExtensionClient) GetConnecotrs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetConnectorsResponse, error) {
	out := new(GetConnectorsResponse)
	err := c.cc.Invoke(ctx, "/service.CarthooksExtension/GetConnecotrs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carthooksExtensionClient) GetResource(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetResourcesResponse, error) {
	out := new(GetResourcesResponse)
	err := c.cc.Invoke(ctx, "/service.CarthooksExtension/GetResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CarthooksExtensionServer is the server API for CarthooksExtension service.
// All implementations must embed UnimplementedCarthooksExtensionServer
// for forward compatibility
type CarthooksExtensionServer interface {
	GetCustomFieldTypes(context.Context, *Empty) (*GetFieldsResponse, error)
	GetModels(context.Context, *Empty) (*GetModelsResponse, error)
	GetI18NPack(context.Context, *Empty) (*GetI18NPackResponse, error)
	GetServices(context.Context, *Empty) (*GetServicesResponse, error)
	GetConnecotrs(context.Context, *Empty) (*GetConnectorsResponse, error)
	GetResource(context.Context, *Empty) (*GetResourcesResponse, error)
	mustEmbedUnimplementedCarthooksExtensionServer()
}

// UnimplementedCarthooksExtensionServer must be embedded to have forward compatible implementations.
type UnimplementedCarthooksExtensionServer struct {
}

func (UnimplementedCarthooksExtensionServer) GetCustomFieldTypes(context.Context, *Empty) (*GetFieldsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomFieldTypes not implemented")
}
func (UnimplementedCarthooksExtensionServer) GetModels(context.Context, *Empty) (*GetModelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModels not implemented")
}
func (UnimplementedCarthooksExtensionServer) GetI18NPack(context.Context, *Empty) (*GetI18NPackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetI18NPack not implemented")
}
func (UnimplementedCarthooksExtensionServer) GetServices(context.Context, *Empty) (*GetServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServices not implemented")
}
func (UnimplementedCarthooksExtensionServer) GetConnecotrs(context.Context, *Empty) (*GetConnectorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConnecotrs not implemented")
}
func (UnimplementedCarthooksExtensionServer) GetResource(context.Context, *Empty) (*GetResourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResource not implemented")
}
func (UnimplementedCarthooksExtensionServer) mustEmbedUnimplementedCarthooksExtensionServer() {}

// UnsafeCarthooksExtensionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CarthooksExtensionServer will
// result in compilation errors.
type UnsafeCarthooksExtensionServer interface {
	mustEmbedUnimplementedCarthooksExtensionServer()
}

func RegisterCarthooksExtensionServer(s grpc.ServiceRegistrar, srv CarthooksExtensionServer) {
	s.RegisterService(&CarthooksExtension_ServiceDesc, srv)
}

func _CarthooksExtension_GetCustomFieldTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarthooksExtensionServer).GetCustomFieldTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.CarthooksExtension/GetCustomFieldTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarthooksExtensionServer).GetCustomFieldTypes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CarthooksExtension_GetModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarthooksExtensionServer).GetModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.CarthooksExtension/GetModels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarthooksExtensionServer).GetModels(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CarthooksExtension_GetI18NPack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarthooksExtensionServer).GetI18NPack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.CarthooksExtension/GetI18nPack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarthooksExtensionServer).GetI18NPack(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CarthooksExtension_GetServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarthooksExtensionServer).GetServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.CarthooksExtension/GetServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarthooksExtensionServer).GetServices(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CarthooksExtension_GetConnecotrs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarthooksExtensionServer).GetConnecotrs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.CarthooksExtension/GetConnecotrs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarthooksExtensionServer).GetConnecotrs(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CarthooksExtension_GetResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarthooksExtensionServer).GetResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.CarthooksExtension/GetResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarthooksExtensionServer).GetResource(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// CarthooksExtension_ServiceDesc is the grpc.ServiceDesc for CarthooksExtension service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CarthooksExtension_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.CarthooksExtension",
	HandlerType: (*CarthooksExtensionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCustomFieldTypes",
			Handler:    _CarthooksExtension_GetCustomFieldTypes_Handler,
		},
		{
			MethodName: "GetModels",
			Handler:    _CarthooksExtension_GetModels_Handler,
		},
		{
			MethodName: "GetI18nPack",
			Handler:    _CarthooksExtension_GetI18NPack_Handler,
		},
		{
			MethodName: "GetServices",
			Handler:    _CarthooksExtension_GetServices_Handler,
		},
		{
			MethodName: "GetConnecotrs",
			Handler:    _CarthooksExtension_GetConnecotrs_Handler,
		},
		{
			MethodName: "GetResource",
			Handler:    _CarthooksExtension_GetResource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Extension.proto",
}
