// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: fieldtype.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StorageType int32

const (
	StorageType_STORAGE_UNSPECIFIED StorageType = 0
	StorageType_STORAGE_STRING      StorageType = 1
	StorageType_STORAGE_NUMBER      StorageType = 2
	StorageType_STORAGE_BLOB        StorageType = 3
)

// Enum value maps for StorageType.
var (
	StorageType_name = map[int32]string{
		0: "STORAGE_UNSPECIFIED",
		1: "STORAGE_STRING",
		2: "STORAGE_NUMBER",
		3: "STORAGE_BLOB",
	}
	StorageType_value = map[string]int32{
		"STORAGE_UNSPECIFIED": 0,
		"STORAGE_STRING":      1,
		"STORAGE_NUMBER":      2,
		"STORAGE_BLOB":        3,
	}
)

func (x StorageType) Enum() *StorageType {
	p := new(StorageType)
	*p = x
	return p
}

func (x StorageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorageType) Descriptor() protoreflect.EnumDescriptor {
	return file_fieldtype_proto_enumTypes[0].Descriptor()
}

func (StorageType) Type() protoreflect.EnumType {
	return &file_fieldtype_proto_enumTypes[0]
}

func (x StorageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorageType.Descriptor instead.
func (StorageType) EnumDescriptor() ([]byte, []int) {
	return file_fieldtype_proto_rawDescGZIP(), []int{0}
}

type CompressType int32

const (
	CompressType_NONE  CompressType = 0
	CompressType_GZIP  CompressType = 1
	CompressType_BZIP2 CompressType = 2
	CompressType_ZIP   CompressType = 3
)

// Enum value maps for CompressType.
var (
	CompressType_name = map[int32]string{
		0: "NONE",
		1: "GZIP",
		2: "BZIP2",
		3: "ZIP",
	}
	CompressType_value = map[string]int32{
		"NONE":  0,
		"GZIP":  1,
		"BZIP2": 2,
		"ZIP":   3,
	}
)

func (x CompressType) Enum() *CompressType {
	p := new(CompressType)
	*p = x
	return p
}

func (x CompressType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompressType) Descriptor() protoreflect.EnumDescriptor {
	return file_fieldtype_proto_enumTypes[1].Descriptor()
}

func (CompressType) Type() protoreflect.EnumType {
	return &file_fieldtype_proto_enumTypes[1]
}

func (x CompressType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompressType.Descriptor instead.
func (CompressType) EnumDescriptor() ([]byte, []int) {
	return file_fieldtype_proto_rawDescGZIP(), []int{1}
}

type GetFieldsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields []*CustomFieldType `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *GetFieldsResponse) Reset() {
	*x = GetFieldsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fieldtype_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFieldsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFieldsResponse) ProtoMessage() {}

func (x *GetFieldsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fieldtype_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFieldsResponse.ProtoReflect.Descriptor instead.
func (*GetFieldsResponse) Descriptor() ([]byte, []int) {
	return file_fieldtype_proto_rawDescGZIP(), []int{0}
}

func (x *GetFieldsResponse) GetFields() []*CustomFieldType {
	if x != nil {
		return x.Fields
	}
	return nil
}

// message field to extend system field datatype. such as map, cad file, lbs locatin, etc.
type CustomFieldType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name             string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type             StorageType `protobuf:"varint,2,opt,name=type,proto3,enum=service.StorageType" json:"type,omitempty"`
	InputComponent   *Assets     `protobuf:"bytes,3,opt,name=input_component,json=inputComponent,proto3" json:"input_component,omitempty"`
	SettingComponent *Assets     `protobuf:"bytes,4,opt,name=setting_component,json=settingComponent,proto3" json:"setting_component,omitempty"`
	ShowComponent    *Assets     `protobuf:"bytes,5,opt,name=show_component,json=showComponent,proto3" json:"show_component,omitempty"`
}

func (x *CustomFieldType) Reset() {
	*x = CustomFieldType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fieldtype_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomFieldType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomFieldType) ProtoMessage() {}

func (x *CustomFieldType) ProtoReflect() protoreflect.Message {
	mi := &file_fieldtype_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomFieldType.ProtoReflect.Descriptor instead.
func (*CustomFieldType) Descriptor() ([]byte, []int) {
	return file_fieldtype_proto_rawDescGZIP(), []int{1}
}

func (x *CustomFieldType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomFieldType) GetType() StorageType {
	if x != nil {
		return x.Type
	}
	return StorageType_STORAGE_UNSPECIFIED
}

func (x *CustomFieldType) GetInputComponent() *Assets {
	if x != nil {
		return x.InputComponent
	}
	return nil
}

func (x *CustomFieldType) GetSettingComponent() *Assets {
	if x != nil {
		return x.SettingComponent
	}
	return nil
}

func (x *CustomFieldType) GetShowComponent() *Assets {
	if x != nil {
		return x.ShowComponent
	}
	return nil
}

var File_fieldtype_proto protoreflect.FileDescriptor

var file_fieldtype_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x0c, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x45, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a,
	0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22,
	0xff, 0x01, 0x0a, 0x0f, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x38, 0x0a, 0x0f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x6f,
	0x6e, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x52, 0x0e, 0x69, 0x6e, 0x70,
	0x75, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x12, 0x3c, 0x0a, 0x11, 0x73,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x52, 0x10, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x12, 0x36, 0x0a, 0x0e, 0x73, 0x68, 0x6f,
	0x77, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x73, 0x73, 0x65,
	0x74, 0x73, 0x52, 0x0d, 0x73, 0x68, 0x6f, 0x77, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x2a, 0x60, 0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x17, 0x0a, 0x13, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x47, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x4f,
	0x52, 0x41, 0x47, 0x45, 0x5f, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x12, 0x0a,
	0x0e, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x47, 0x45, 0x5f, 0x4e, 0x55, 0x4d, 0x42, 0x45, 0x52, 0x10,
	0x02, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x47, 0x45, 0x5f, 0x42, 0x4c, 0x4f,
	0x42, 0x10, 0x03, 0x2a, 0x36, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x08, 0x0a,
	0x04, 0x47, 0x5a, 0x49, 0x50, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x5a, 0x49, 0x50, 0x32,
	0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x5a, 0x49, 0x50, 0x10, 0x03, 0x42, 0x28, 0x5a, 0x26, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x61, 0x72, 0x74, 0x68, 0x6f,
	0x6f, 0x6b, 0x73, 0x2f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fieldtype_proto_rawDescOnce sync.Once
	file_fieldtype_proto_rawDescData = file_fieldtype_proto_rawDesc
)

func file_fieldtype_proto_rawDescGZIP() []byte {
	file_fieldtype_proto_rawDescOnce.Do(func() {
		file_fieldtype_proto_rawDescData = protoimpl.X.CompressGZIP(file_fieldtype_proto_rawDescData)
	})
	return file_fieldtype_proto_rawDescData
}

var file_fieldtype_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_fieldtype_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fieldtype_proto_goTypes = []interface{}{
	(StorageType)(0),          // 0: service.StorageType
	(CompressType)(0),         // 1: service.CompressType
	(*GetFieldsResponse)(nil), // 2: service.GetFieldsResponse
	(*CustomFieldType)(nil),   // 3: service.CustomFieldType
	(*Assets)(nil),            // 4: service.Assets
}
var file_fieldtype_proto_depIdxs = []int32{
	3, // 0: service.GetFieldsResponse.fields:type_name -> service.CustomFieldType
	0, // 1: service.CustomFieldType.type:type_name -> service.StorageType
	4, // 2: service.CustomFieldType.input_component:type_name -> service.Assets
	4, // 3: service.CustomFieldType.setting_component:type_name -> service.Assets
	4, // 4: service.CustomFieldType.show_component:type_name -> service.Assets
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_fieldtype_proto_init() }
func file_fieldtype_proto_init() {
	if File_fieldtype_proto != nil {
		return
	}
	file_assets_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_fieldtype_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFieldsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fieldtype_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomFieldType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fieldtype_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fieldtype_proto_goTypes,
		DependencyIndexes: file_fieldtype_proto_depIdxs,
		EnumInfos:         file_fieldtype_proto_enumTypes,
		MessageInfos:      file_fieldtype_proto_msgTypes,
	}.Build()
	File_fieldtype_proto = out.File
	file_fieldtype_proto_rawDesc = nil
	file_fieldtype_proto_goTypes = nil
	file_fieldtype_proto_depIdxs = nil
}
